buildNumber: unknown
buildTime: unknown
gitRevision: unknown
gitBranch: unknown

spring:
  datasource:
    url: jdbc:h2:mem:ecommerce_order_mysql
    driverClassName: org.h2.Driver
    username: sa
    password: 123456

